export const NEWS_API_URL = 'https://nomoreparties.co/news/v2/everything';
export const NEWS_API_KEY = '62c9a6e8890849328a72ca82e14e0097';
export const GITHUB_API_URL = 'https://api.github.com/repos/tina-dumilina/news-analyzer/commits';
export const CARDS_TO_RENDER = 3;
export const DAY = 24 * 60 * 60 * 1000;
export const WEEK = 7 * DAY;
export const WEEK_AGO = new Date(Date.now() - WEEK);
export const PAGE_SIZE_LIMIT = 100;
export const COMMITS_NUMBER_LIMIT = 20;